### ISSUE TITLE
Question - repackage existing .deb libraries?

### ISSUE THREAD

**Issue by jhelmink** [rednoah/ant-spk#1]
Random question, could this be used to repackage some existing .deb packages for Synology?

There are two libraries that would be useful for Synology users running Plex, but no way to install them and their dependencies...

1. ocl-icd-libopencl1 
2. beignet-opencl-icd

**Comment by rednoah** [comment]
Presumably, the issue here is cross-compiling these libraries for all Synology platforms, and not packaging. `ant-spk` can help you do the latter, but if the former was possible (i.e. easy) then Plex would already package those libraries in the first place.
